---
- name: Change service status to stopped  
  hosts: all
  become: true
  vars:
    servicename:

  tasks:
    - name: Change service status to stoppped
      systemd:
        name: {{ servicename }}
        state: stopped
      register: service_status

    - name: Display service status
      debug:
        var: service_status
