---
- name: Show Uptime
  hosts: all
  became: true

  tasks:
    - name: Run uptime command
      command: uptime
      register: uptime_output

    - name: Display uptime
      debug:
        var: uptime_output.stdout_lines
