---
- name: Install specified app on Linux
  hosts: all
  become: true
  vars:
    appname:

  tasks:
    - name: Install specified package
      apt:
        name: '{{ appname }}'
        state: present
